name: minishift
on: 
  push:
    branches: 
      - dev
jobs:
  minikube:
    env:
      mode: minishift
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
          set -x

          sudo apt update
          sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
          sudo usermod -a -G libvirt $(whoami)
          sudo curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04 -o /usr/local/bin/docker-machine-driver-kvm
          sudo chmod +x /usr/local/bin/docker-machine-driver-kvm
          systemctl is-active libvirtd
          sudo virsh net-list --all
          sudo virsh net-autostart default
          wget https://github.com/minishift/minishift/releases/download/v1.34.3/minishift-1.34.3-linux-amd64.tgz
          gunzip minishift-1.34.3-linux-amd64.tgz
          tar xf minishift-1.34.3-linux-amd64.tar
          rm minishift-1.34.3-linux-amd64.tar
          sudo mv minishift-1.34.3-linux-amd64/minishift /usr/local/bin
          echo $PATH
          minishift version
          minishift start
